### ISSUE TITLE
Assign VM ID (host ID) to cb-network agent

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-larva#101]
**What would you like to be added**
: A method to assign VM ID to the cb-network agent

**Why is this needed**
: It's because a host needs a unique VM ID to join the CLADNet and obtain an IP address.

**Comment by hermitkim1** [comment]
(Suppose that an MCIS has 3 VMs)

### [Plan]
- Use CB-Tumblebug API as follows:
  - Send a command to specified VM - `/ns/{nsId}/cmd/mcis/{mcisId}/vm/{vmId}`
- Call the API 3 times to assign the VM ID to the corresponding cb-network agent

**Comment by hermitkim1** [comment]
The base script for this: [change-mcis-hostname.sh](https://github.com/cloud-barista/cb-tumblebug/blob/master/src/testclient/scripts/sequentialFullTest/change-mcis-hostname.sh) in CB-Tumblebug

**Comment by seokho-son** [comment]
@hermitkim1 
- FYI 1
CB-TB에서 MCIS 생성 과정에 CB-Dragonfly의 Agent를 설치하는 코드도 들어있습니다. 참고하시면 되겠어요~ ^^ 
(CB-Dragonfly에 Agent 설치 요청 API가 있어서, CB-TB가 필요한 정보를 해당 API로 넘겨서 CB-Dragonfly가 Agent를 설치하게 만들고, 정상 설치 여부를 검증)
https://github.com/cloud-barista/cb-tumblebug/blob/affc59d30ae08b0cc6e3c3f6ef55a0fa40322e57/src/core/mcis/control.go#L2265

- FYI 2
CB-TB가 Milkyway Agent를 설치하던 코드 (원격 커멘드 기능을 사용하여 MCIS의 모든 VM에 API 서버 자체를 설치함)
https://github.com/cloud-barista/cb-tumblebug/blob/affc59d30ae08b0cc6e3c3f6ef55a0fa40322e57/src/core/mcis/control.go#L439

**Comment by hermitkim1** [comment]
@seokho-son 

정보 공유 감사합니다 🙏 

두 스크립트 참고하여 MCIS에 cb-network agent 설치 진행해 보겠습니다 😄

**Comment by hermitkim1** [comment]
This issue has been resolved.
