### ISSUE TITLE
Update Go version on workflows

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-larva#139]
**What would you like to be enhanced**
: I'd like to update Go version on workflows

**Why is this needed**
: 

**Proposed solution**
: The proposed solution is to change `go-version: [ 1.15.x ]` to `go-version: [ 1.16.x ]`

The related workflows:
- [Line 24 in build-on-pull-request.yaml](https://github.com/cloud-barista/cb-larva/blob/24b3878535211d6b7ebd68f65931a7436c1ff4fc/.github/workflows/build-on-pull-request.yml#L24)
- [Line 33 in lint-on-push.yml](https://github.com/cloud-barista/cb-larva/blob/24b3878535211d6b7ebd68f65931a7436c1ff4fc/.github/workflows/lint-on-push.yml#L33)

**Comment by shivamgupta-sg** [comment]
can you assign this to me

**Comment by ChobobDev** [comment]
I would love to have a go with this issue.

Thank you

**Comment by shivamgupta-sg** [comment]
I would love to solve the issue.
Thanks

**Comment by hermitkim1** [comment]
Thank you for your interest in this issue.

I got an email from @shivamgupta-sg before.
Thus, I'd like to assign this issue to @shivamgupta-sg.

I am sorry for the inconvenience to @ChobobDev 🙏

**Comment by ChobobDev** [comment]
@hermitkim1  Thank you for the confIrmation.

**Comment by shivamgupta-sg** [comment]
Thanks @hermitkim1

**Comment by hermitkim1** [comment]
@shivamgupta-sg Thank YOU! 😄

**Comment by shivamgupta-sg** [comment]
@hermitkim1 Raised PR #150 for the same
