### ISSUE TITLE
Provide APIs based on gRPC

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-larva#142]
**What would you like to be added**
: I'd like to provide APIs based on gRPC and also cover RESTful APIs by gRPC Gateway.

You can find its details in Discussion #141 😄 

**Why is this needed**
:

**Comment by hermitkim1** [comment]
Study and consider creating a YAML file of `[gRPC 서버, 클라이언트 환경설정 관련]` (Thanks, @jihoon-seo)

Source: https://github.com/cloud-barista/cb-larva/pull/143#issuecomment-918715828

**Comment by hermitkim1** [comment]
I'd like to add gRPC Gateway to the current gRPC base (`cloud_adaptive_network.proto`) and compile it.
