### ISSUE TITLE
Release v0.0.8 

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-larva#246]
- [x] Test and debug cb-network system
   - [x] cb-network controller
   - [x] cb-network service
   - [x] cb-network admin-web
   - [x] cb-network agent
   - [x] cb-network test-client (i.e., integration test)
- [x] Update docs/markdown
- [x] Deliver execution files to HTTP file server

**Comment by seokho-son** [comment]
v0.0.8 ;)
