### ISSUE TITLE
Reduce the complexity of updating the networking rule

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-larva#316]
**What would you like to be enhanced**
: I'd like to reduce complexity in networking rule updates and efficiently operate the cb-network (i.e., Cloud Adaptive Network).

**Why is this needed**
: Its complexity is $n^2$ to update the networking rule. It's inefficient.
: For example, just 100 peers participated. When a peer is updated, it is updated 10,000 times...

**Proposed solution**
: To break the data structure of the networking rule into smaller units
: To simplify the mechanism according to the smaller data unit

**Comment by seokho-son** [comment]
https://www.stratechi.com/wp-content/uploads/2018/03/Stratechi-Manage-Complexity-Business-Strategy-Reduce.jpg

:)

**Comment by yunkon-kim** [comment]
@seokho-son, thanks for your comment !

I think I'll focus on segmentation and rearrangement ^^
