### ISSUE TITLE
A plan to construct a MCIS-based cb-network test environment

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-larva#89]
### 1. MCIS 생성 및 삭제 테스트 수행
1. 각 CSP(최소 3개)의 crediential 생성 가이드 작성 - [참고](https://github.com/cloud-barista/cb-coffeehouse/wiki/A-step-by-step-guide-to-creating-credentials-of-each-cloud-service-provider)
    - 추후 [CB-Tumblebug's Test README](https://github.com/cloud-barista/cb-tumblebug/blob/master/test/official/README.md) 개선에 활용 예정
2. CB-Spider 컨테이너 구동 by [CB-TB's setcbsp.sh](https://github.com/cloud-barista/cb-tumblebug/blob/master/assets/scripts/setcbsp.sh) (컨테이너 구동)
3. CB-Tumblebug 구동 by [setcbtb.sh](https://github.com/cloud-barista/cb-tumblebug/blob/master/assets/scripts/setcbtb.sh) (소스코드 빌드)
4. credentials.conf 작성
5. Test 스크립트를 활용한 MCIS 생성 및 삭제 테스트 수행
```
./testAll-mcis-mcir-ns-cloud.sh aws 2 kimy
./cleanAll-mcis-mcir-ns-cloud.sh aws 2 kimy

./testAll-mcis-mcir-ns-cloud.sh gcp 2 kimy
./cleanAll-mcis-mcir-ns-cloud.sh gcp 2 kimy

./testAll-mcis-mcir-ns-cloud.sh azure 2 kimy
./cleanAll-mcis-mcir-ns-cloud.sh azure 2 kimy
```

### 2. MCIS에 cb-network controller 및 agent 배치
[TBD]
cb-network 설치 스크립트 작성
deploy-xxx.sh 를 활용하여 배치

### 3. cb-network 테스트 수행
[TBD]

**Comment by seokho-son** [comment]
참고로 2 번은 적극 활용하는 스크립트가 아니라서.
스파이더 0.2 버전에 머물러 있을 것 같습니다. 참고만 하시길!^^

**Comment by hermitkim1** [comment]
@seokho-son (CC. @powerkimhub)

말씀 감사합니다!

2.0 버전으로 진행해도 MCIS 생성에는 지장이 없을것 같아 진행하고 있었는데요.

혹시 추천해주실 버전 Pair가 있으면 말씀해주세요 😃

**Comment by seokho-son** [comment]
@hermitkim1 오늘 중에 CB-TB 프리릴리스 하나 찍고 알려드릴게요. 

https://github.com/cloud-barista/cb-spider/releases/tag/v0.3.4
https://github.com/cloud-barista/cb-dragonfly/releases/tag/v0.3.2

함께 동작 테스트 완료된 버전으로.. ^^

**Comment by seokho-son** [comment]
@hermitkim1

CB-Tumblebug v0.3.4 프리릴리스 공유 드립니다.. ^^
https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.3.4

CB-Tumblebug v0.3.4 which works with following pre-releases.

- CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.3.5)
- CB-Dragonfly (https://github.com/cloud-barista/cb-dragonfly/releases/tag/v0.3.2)

**Comment by hermitkim1** [comment]
@powerkimhub 

CB-Spider AdminWeb과 관련하여 **문의사항**이 있습니다.

`./testAll-mcis-mcir-ns-cloud.sh aws 1 kimyk` 실행했을때 아래 오류가 발생하여 디버깅을 수행하고 있는데요. 
```
####################################################################
## 3. vNet: Create
####################################################################
[For AWS]
{
   "message" : "{\"message\":\"AuthFailure: AWS was not able to validate the provided access credentials\\n\\tstatus code: 401, request id: d3a32a82-3559-40bf-9097-a1973f5289bc\"}\n"
}
```

1. CB-Spider(v0.3.5) 컨테이너 구동 및 CB-Tumblebug(v0.3.4) 소스기반 구동을 한 상황에서
2. `./testAll-mcis-mcir-ns-cloud.sh aws 1 kimyk` 를 실행 하였고요.
3. 위 오류를 접하였습니다.
4. 우선적으로 Credential의 정상 여부 확인을 위해 CB-Spider AdminWeb에서 credential 추가를 시도했는데 아래와 같이 Host IP/Domain이 없어 발생하는 것으로 보이는 오류가 있습니다.

![image](https://user-images.githubusercontent.com/7975459/117766372-6ffc1100-b26a-11eb-84e8-c29da9ec65f8.png)

**문의사항: 이와 관련하여 CB-Spider 컨테이너 구동시 추가로 설정해야하는 부분이 있을지 문의드립니다.**

**Comment by hermitkim1** [comment]
@powerkimhub @seokho-son @jihoon-seo 

도와주시고 해결해주셔서 감사합니다. 🙏 

당분간 CB-Larva에서 MCIS 생성 관련해서는 아래 버전을 활용하겠습니다.
- CB-Spider latest (5fa061356b389cdfec8a6e90aa1a99369f1baca0)
  - 이후 CB-Spider v0.3.14 릴리스 시 이를 활용(현재 CB-Spider tag는 v0.3.13)
- CB-Tumblebug v0.3.6

**Comment by seokho-son** [comment]
@hermitkim1 CB-Tumblebug 프리릴리스의 경우, Spider 및 Dragonfly 프리릴리스로 기본 테스트를 완료한 다음에 릴리스하고 있습니다~ 그래서 Spider latest를 계속 업데이트해서 연동하면, TB는 정상 동작을 보장할 수는 없습니다. (클라우드별로 상황이 달라서 Spider의 변화에 따라 여파가 좀 있습니다.) 참고하시기 바랍니다~~ 오류가 발생하면 리포트를 해주셔도 좋아요 ~

**Comment by hermitkim1** [comment]
@seokho-son

넵! 말씀해주신 부분 잘 이해했습니다.

위 [질문](https://github.com/cloud-barista/cb-larva/issues/89#issuecomment-837901268)과 관련하여 CB-Spider 컨테이너 구동시 AdminWeb을 사용할 수 있도록 해결해 주셔서요. 이를 반영하고자 CB-Spider lastest를 사용하려고 했는데요.

CB-Spider v0.3.14 릴리스 전까지 CB-Spider v0.3.8로 MCIS 생성 진행하는것이 좋을 것 같습니다. 😄 

이후 v0.3.14 활용해보고 이슈가 있으면 리포트 하겠습니다.

**Comment by hermitkim1** [comment]
This issue has been resolved May 11, 2021.

CB-Spider v0.3.8 and CB-Tumblebug v0.3.6 has been deployed for the MCIS-based cb-network test environment,
